name: mesh-runners

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Runner Node
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          REG_PORT: ${{ secrets.REG_PORT }}
          SERVER_PUBKEY: ${{ secrets.SERVER_PUBKEY }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          SSH_PUBKEY: ${{ secrets.SSH_PUBKEY }}
          NODE_ID: ${{ matrix.node_id }}
        run: |
          chmod +x agent/entrypoint.sh
          ./agent/entrypoint.sh
